fructose: drop explicit test_base<test_container> constructor
The code states:
  // compiler-generated default constructor would be OK
  // but gives warnings with GCC's -Weffc++.

We didn't see that warning anywhere, but recently we got a new error on
Debian Bookworm with gcc version 12.2.0 (Debian 12.2.0-14).

gcc on Debian Bookworm we get:
  In file included from ../tools/fructose/fructose.h:26,
                 from ../AdsLibOOITest/main.cpp:17:
  ../tools/fructose/test_base.h:280:31: error: expected unqualified-id before ‘)’ token
  280 |     test_base<test_container>()

So we simply drop the code.

Reviewed-by: Steffen Dirkwinkel <s.dirkwinkel@beckhoff.com>
Signed-off-by: Patrick Bruenn <p.bruenn@beckhoff.com>