ci: upgrade meson on Windows
Currently meson 1.2.0 is preinstalled in the newest build machines, but
that version seems broken:
$ meson setup build -Dwerror=false -Dcpp_args="-D_CRT_NONSTDC_NO_WARNINGS=1, -D_CRT_SECURE_NO_WARNINGS=1, -DNOMINMAX=1" -Dtcadsdll_include=c:\TwinCAT\AdsApi\TcAdsDll\Include -Dtcadsdll_lib=c:\TwinCAT\AdsApi\TcAdsDll\x64\lib
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 194, in run
  File "mesonbuild\msetup.py", line 358, in run
  File "mesonbuild\msetup.py", line 183, in generate
  File "mesonbuild\msetup.py", line 228, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 2997, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 164, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 198, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 635, in assignment
  File "mesonbuild\interpreterbase\interpreterbase.py", line 212, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 251, in evaluate_arraystatement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 593, in reduce_arguments
  File "mesonbuild\interpreterbase\interpreterbase.py", line 593, in <listcomp>
  File "mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
  [Previous line repeated 4 more times]
  File "mesonbuild\interpreterbase\decorators.py", line 109, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
  File "mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 1774, in func_dependency
  File "mesonbuild\interpreter\dependencyfallbacks.py", line 355, in lookup
  File "mesonbuild\interpreter\dependencyfallbacks.py", line 87, in _do_dependency
  File "mesonbuild\dependencies\detect.py", line 115, in find_external_dependency
  File "mesonbuild\dependencies\detect.py", line 193, in _build_external_dependency_list
  File "collections\__init__.py", line 1123, in __getitem__
  File "mesonbuild\dependencies\detect.py", line 39, in __missing__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonbuild.dependencies.misc'
The Meson build system
Version: 1.2.0

So we force an upgrade, which installs 1.2.1 at the moment and this
seems to fix our issue for now.

Signed-off-by: Patrick Bruenn <p.bruenn@beckhoff.com>