ci: fix build with gcc 15.1.1 on arch linux
Since 1st May our nightly is failing on arch linux. That was the first
pipeline upgrading from gcc 14.2.1 to gcc 15.1.1. It seems that compile
became stricter or buggy. At least it was unable to autogenerate our
custom deleter anymore[1]:
    inlined from ‘AdsHandle AdsDevice::GetHandle(uint32_t) const’ at ../AdsLib/AdsDevice.cpp:60:63:
/usr/include/c++/15.1.1/bits/std_function.h:393:17: error: ‘<anonymous>’ may be used uninitialized [-Werror=maybe-uninitialized]
  393 |             __x._M_manager(_M_functor, __x._M_functor, __clone_functor);
      |             ~~~~^~~~~~~~~~
/usr/include/c++/15.1.1/bits/std_function.h: In member function ‘AdsHandle AdsDevice::GetHandle(uint32_t) const’:
/usr/include/c++/15.1.1/bits/std_function.h:269:7: note: by argument 2 of type ‘const std::_Any_data&’ to ‘static bool std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_manager(std::_Any_data&, const std::_Any_data&, std::_Manager_operation) [with _Res = long int; _Functor = AdsDevice::GetHandle(uint32_t) const::<lambda(uint32_t)>; _ArgTypes = {unsigned int}]’ declared here
  269 |       _M_manager(_Any_data& __dest, const _Any_data& __source,
      |       ^~~~~~~~~~
../AdsLib/AdsDevice.cpp:60:63: note: ‘<anonymous>’ declared here
   60 |     return {new uint32_t {offset}, {[](uint32_t){ return 0; }}};
      |

So here we go and create a static functor used as a dummy deleter for
AdsHandles.

[1] https://git.beckhoff.dev/beckhoff/AdsLib/-/jobs/2126051

Signed-off-by: Patrick Bruenn <p.bruenn@beckhoff.com>