RouterAccess: finally drop useless const from members
MSVC 19.31.31107 is unhappy with them:
../AdsLib/RouterAccess.cpp(66): error C2280: 'bhf::ads::SearchPciSlotResNew::SearchPciSlotResNew(void)': attempting to reference a deleted function
../AdsLib/RouterAccess.cpp(38): note: compiler has generated 'bhf::ads::SearchPciSlotResNew::SearchPciSlotResNew' here
../AdsLib/RouterAccess.cpp(38): note: 'bhf::ads::SearchPciSlotResNew::SearchPciSlotResNew(void)': function was implicitly deleted because 'bhf::ads::SearchPciSlotResNew' has an uninitialized const-qualified data member 'bhf::ads::SearchPciSlotResNew::lePciRegViaPorts'

These const members were a bad idea in the first place so we drop them
here, again.

Reported-by: Marcus Sonestedt <marcus.s.lindblom@gmail.com>
Signed-off-by: Patrick Bruenn <p.bruenn@beckhoff.com>